const MEMBERS = [
  {
    id: 1,
    name: "Abishek",
    img: "/images/Abishek.jpg",
    role: "President & Operations Head",
    linkedIn: "https://www.linkedin.com/in/abishekbr1/",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 2,
    name: "Vikas",
    img: "/images/Vikas.jpg",
    role: "Vice President",
    linkedIn: "https://www.linkedin.com/in/vikas-kumar-7b0451128/",
    instagram: "",
    gitHub: "",
    facebook: "",
  },

  {
    id: 3,
    name: "Divya",
    img: "/images/Divya.jpg",
    role: "Digital Marketing Head",
    linkedIn: "https://www.linkedin.com/in/divya-khurana-7331ba261/",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 4,
    name: "Sockalingam",
    img: "/images/Sockalingam.jpg",
    role: "Treasurer",
    linkedIn: "https://www.linkedin.com/in/sockalingam-saravanan-341a9a193/",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 5,
    name: "Ameya",
    img: "/images/Ameya.jpg",
    role: "Technical Head",
    linkedIn: "https://www.linkedin.com/in/ameya-ade-833a16146/",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
];

export default MEMBERS;
