const VOLUNTEERS = [
  {
    id: 1,
    name: "Ashvinjeet Singh",
    img: "",
    role: "Web Developer",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 2,
    name: "Gagandeep Singh",
    img: "",
    role: "Web Developer",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 3,
    name: "Karthi Krishnamurthi",
    img: "Web Developer",
    role: "",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 4,
    name: "Prableen Kaur Sachdeva",
    img: "Web Developer",
    role: "",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 5,
    name: "Tarun Vignesh Selvabalaji",
    img: "",
    role: "Web Developer",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 6,
    name: "Shivani Sharma",
    img: "Finance Associate",
    role: "",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 7,
    name: "Amandeep Singh",
    img: "",
    role: "Operations Coordinator",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 8,
    name: "Gokul S",
    img: "",
    role: "Operations Coordinator",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 9,
    name: "Manoj Chetty",
    img: "",
    role: "Operations Coordinator",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 10,
    name: "Suhani Prajapati",
    img: "",
    role: "Digital Marketing Associate",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 11,
    name: "Shreya Bille",
    img: "",
    role: "Digital Marketing Associate",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 12,
    name: "Vikram Singh Bedi",
    img: "",
    role: "Web Developer",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 13,
    name: "Arman Panjwani",
    img: "",
    role: "Finance Associate",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 14,
    name: "Anand SM",
    img: "",
    role: "Finance Associate",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
  {
    id: 15,
    name: "Muskan Rana",
    img: "",
    role: "Operations Coordinator",
    linkedIn: "",
    instagram: "",
    gitHub: "",
    facebook: "",
  },
];

export default VOLUNTEERS;
